import Head from "next/head"
import NavBar from '../ui/navBar';
export default function Home() {

  const logo = {
    name : "Labrador Breeder",
    url: "/"
  }

  const menuItems = [{name: "Dogs", url: '/'},{name: "Puppies", url: '/'}, {name: "About", url: "/"}, {name: "Blog", url: "/"}, {name: "Contact Us", url: '/', button: true}]
    return (
        <>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
          
          <link
            rel="stylesheet"
            href='https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800;900&family=Mulish:ital,wght@0,300;0,400;0,500;0,600;0,700;0,800;0,900;0,1000;1,400;1,500;1,600;1,700;1,800;1,900&display=swap'
          />
        </Head>
        <main>
            <NavBar logo={logo} links={menuItems}/>
        </main>
        </>
    )

  }
