import Head from "next/head"
import NavBar from '../ui/navBar';
export default function Home() {

  const logo = {
    name : "Labrador Breeder",
    url: "/"
  }

  const menuItems = [{name: "Dogs", url: '/'},{name: "Puppies", url: '/'}, {name: "About", url: "/"}, {name: "Blog", url: "/"}, {name: "Contact Us", url: '/'}]
    return (
        <>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
          <link
            rel="preload"
            href="https://fonts.gstatic.com/s/inter/v7/UcCORTjFwYhpQIWo_18E_BX2lCsDjGQBZ8oU.woff2"
            as="font"
            type="font/woff2"
            crossorigin
          />
          <link
            rel="stylesheet"
            href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800;900&display=swap"
          />
        </Head>
        <main>
            <NavBar logo={logo} links={menuItems}/>
        </main>
        </>
    )

  }
